DROP TABLE IF EXISTS CADENA;
CREATE TABLE CADENA
(
    ID  INT PRIMARY KEY,
    NAME VARCHAR(20),
    DESCRIPCION VARCHAR(256)
);


DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES
(
    BRAND_ID  INT,
    START_DATE DATE,
    END_DATE DATE,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DOUBLE,
    CURR VARCHAR(3)
);

ALTER TABLE PRICES
    ADD FOREIGN KEY (BRAND_ID)
        REFERENCES CADENA(ID);

